server:
  port: 8090
  servlet:
    context-path: /tmall-service
spring:
  datasource:
    druid:
      max-active: 3
      min-idle: 0
      max-wait: 300000
      max-evictable-idle-time-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-on-return: false
      test-on-borrow: true
      test-while-idle: true
      filter:
        config:
          enabled: true
      url: jdbc:mysql://192.168.2.102:3306/tmall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
      username: tmall
      password: C1JiG51qZPnW5gYIAczJ1aPPF9sPkAvOofQGXor/ictrloCluSk4BYPSwkcx4lcN1DE58FcgPQD+yfRjs025YQ==
      connect-properties:
        config.decrypt: true
        config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIKMRMProkDVCg/TA0yR6/HRy2boGt6sE1rtYe7+v0svv5DUC5YF1RM0aLy+KV6hDh0c+yXq9HFl9WTOgNz+IUkCAwEAAQ==
  redis:
    cluster:
      nodes:
        - 192.168.2.102:6379
        - 192.168.2.102:6380
        - 192.168.2.102:6381
        - 192.168.2.102:6382
        - 192.168.2.102:6383
        - 192.168.2.102:6384
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 60000ms
  application:
    name: tmall-service
  session:
    store-type: redis
    redis:
      namespace: spring:session:tmall
    timeout: 180000
  activiti:
    async-executor-activate: false
    check-process-definitions: false
    history-level: audit

mybatis-plus:
  type-enums-package: net.mshome.twisted.tmall.enumeration
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-handlers-package: net.mshome.twisted.tmall.aop.handler.mybatis
  mapper-locations: classpath:mapper/*Mapper.xml

tmall:
  sync:
    tables: user
