server:
  port: 8090
  servlet:
    context-path: /tmall-service
spring:
  datasource:
    druid:
      max-active: 3
      min-idle: 0
      max-wait: 300000
      max-evictable-idle-time-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-on-return: false
      test-on-borrow: true
      test-while-idle: true
      filter:
        config:
          enabled: true
      connect-properties:
        config.decrypt: true
        config.decrypt.key: ${spring.datasource.druid.connect-properties.public-key}
  application:
    name: tmall-service
  session:
    store-type: redis
    redis:
      namespace: spring:session:tmall
    timeout: 180000
  activiti:
    async-executor-activate: false
    check-process-definitions: false
    history-level: audit
    database-schema-update:

mybatis-plus:
  type-enums-package: net.mshome.twisted.tmall.enumeration
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-handlers-package: net.mshome.twisted.tmall.aop.handler.mybatis
  mapper-locations: classpath:mapper/*Mapper.xml

tmall:
  sync:
    tables: user
