spring:
  datasource:
    druid:
      url: jdbc:mysql://mysql.base-env:3306/tmall?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true
      username: tmall
      password: C1JiG51qZPnW5gYIAczJ1aPPF9sPkAvOofQGXor/ictrloCluSk4BYPSwkcx4lcN1DE58FcgPQD+yfRjs025YQ==
      connect-properties:
        public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIKMRMProkDVCg/TA0yR6/HRy2boGt6sE1rtYe7+v0svv5DUC5YF1RM0aLy+KV6hDh0c+yXq9HFl9WTOgNz+IUkCAwEAAQ==


  redis:
    host: redis.base-env
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 5ms
        max-idle: 8
        min-idle: 0
    database: 1