apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmall
  namespace: twisted-fate
  labels:
    app: tmall
spec:
  replicas: 1
  template:
    metadata:
      name: tmall
      labels:
        app: tmall
    spec:
      containers:
        - name: tmall
          image: tmall-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: ACTIVE_PROFILE
              value: test
          resources:
            requests:
              memory: 100Mi
              cpu: 500m
            limits:
              memory: 500Mi
              cpu: 1000m
          livenessProbe:
            httpGet:
              path: /tmall-service/actuator
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8090
              path: /tmall-service/actuator
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
      restartPolicy: Always
      hostNetwork: false
  selector:
    matchLabels:
      app: tmall
---
apiVersion: v1
kind: Service
metadata:
  name: tmall
  namespace: twisted-fate
spec:
  selector:
    app: tmall
  ports:
    - port: 8090
      targetPort: 8090