apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tmall
  namespace: twisted-fate
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/tmall/`)
      kind: Rule
      services:
        - name: tmall
          port: 8090